// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class userhaspreferredcanonorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userhaspreferredcanonorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201502251210263_user has preferred canon order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
