// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class optiontotranslateepisodesandadaptations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(optiontotranslateepisodesandadaptations));
        
        string IMigrationMetadata.Id
        {
            get { return "201503301626341_option to translate episodes and adaptations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
