// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class actorimdbnameindatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actorimdbnameindatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201503161512450_actor imdbname in database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
