// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class putlimitsbackonactors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(putlimitsbackonactors));
        
        string IMigrationMetadata.Id
        {
            get { return "201502181517015_put limits back on actors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
