// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class givecreditforactorphotos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(givecreditforactorphotos));
        
        string IMigrationMetadata.Id
        {
            get { return "201606031000300_give credit for actor photos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
