// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class nulllatlngisOK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nulllatlngisOK));
        
        string IMigrationMetadata.Id
        {
            get { return "201608101140092_null latlng is OK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
