// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class HolmesLinkwithproperactors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HolmesLinkwithproperactors));
        
        string IMigrationMetadata.Id
        {
            get { return "201609222144363_HolmesLink with proper actors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
