// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class HolmesLinkoptionalshavetobenullables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HolmesLinkoptionalshavetobenullables));
        
        string IMigrationMetadata.Id
        {
            get { return "201609222324456_HolmesLink optionals have to be nullables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
