// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class HolmesLinkandHolmesLinkAppearancetableadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HolmesLinkandHolmesLinkAppearancetableadd));
        
        string IMigrationMetadata.Id
        {
            get { return "201609220841199_HolmesLink and HolmesLinkAppearance table add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
