// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class actorbirthplacesync : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actorbirthplacesync));
        
        string IMigrationMetadata.Id
        {
            get { return "201608101137447_actor birthplace sync"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
