// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class categorisestoriesbycrime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categorisestoriesbycrime));
        
        string IMigrationMetadata.Id
        {
            get { return "201606071204092_categorise stories by crime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
