// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class charuniqueurlnames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(charuniqueurlnames));
        
        string IMigrationMetadata.Id
        {
            get { return "201809281616557_char unique urlnames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
