// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class urlnamesforadaptationslengthsforurlnames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(urlnamesforadaptationslengthsforurlnames));
        
        string IMigrationMetadata.Id
        {
            get { return "201809191531206_url names for adaptations, lengths for url names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
