// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class urlnamesforcharacters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(urlnamesforcharacters));
        
        string IMigrationMetadata.Id
        {
            get { return "201809141515372_url names for characters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
