// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class urlnamesforactors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(urlnamesforactors));
        
        string IMigrationMetadata.Id
        {
            get { return "201809141358494_url names for actors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
