// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class marksinglestorycharacters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(marksinglestorycharacters));
        
        string IMigrationMetadata.Id
        {
            get { return "201807121736185_mark single story characters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
