// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class linksinglestorycharacterstostory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(linksinglestorycharacterstostory));
        
        string IMigrationMetadata.Id
        {
            get { return "201807121741092_link single story characters to story"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
