// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class thiswholethingsmacksofgender : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thiswholethingsmacksofgender));
        
        string IMigrationMetadata.Id
        {
            get { return "201807130936083_this whole thing smacks of gender"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
