// <auto-generated />
namespace HolmesMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class imdbandletterboxdforfilminseries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imdbandletterboxdforfilminseries));
        
        string IMigrationMetadata.Id
        {
            get { return "202101181653544_imdb and letterboxd for film in series"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
